# Generated by Django 4.2.1 on 2023-05-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Enter the city where the team is based.', max_length=100)),
                ('mascot', models.CharField(help_text='Enter the team mascot name.', max_length=100)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the player's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Enter the player's last name.", max_length=100)),
                ('teams', models.ManyToManyField(help_text='Select the teams this player belongs to.', to='team_tracker.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
