# Generated by Django 4.2.1 on 2023-05-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Select the team this player belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='team_tracker.team'),
        ),
    ]
