# Generated by Django 4.2.1 on 2023-05-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tracker', '0002_remove_player_teams_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Select the team this player belongs to.', on_delete=django.db.models.deletion.CASCADE, to='team_tracker.team'),
        ),
    ]
